import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {readJsonLimited} from '@/lib/abyss/request';
import {candidates,winners} from '@/lib/abyss/science';
import {grid} from '@/lib/abyss/tools';
const depth=z.coerce.number().int().min(0).max(11000);
function session(d:number){return `samoa-2026-v1-depth-${d}`}
export async function GET(req:Request){const parsed=depth.safeParse(new URL(req.url).searchParams.get('depth')??2000);if(!parsed.success)return Response.json({error:'Invalid depth'},{status:400});const d=parsed.data,list=candidates(grid,d);try{const result=await env.DB.prepare('SELECT candidate, SUM(minutes) AS minutes FROM votes WHERE session = ? GROUP BY candidate').bind(session(d)).all<{candidate:string;minutes:number}>();const totals=Object.fromEntries(list.map(c=>[c.id,0]));result.results.forEach(r=>{if(Object.hasOwn(totals,r.candidate))totals[r.candidate]=r.minutes});return Response.json({session:session(d),candidates:list,totals,winners:winners(totals)},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'Community voting is temporarily unavailable. Your scientific explorer is unaffected.'},{status:503})}}
export async function POST(req:Request){if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Origin mismatch'},{status:403});let body;try{body=z.object({depth,voter:z.uuid(),candidateId:z.string().max(32)}).parse(await readJsonLimited(req,4096))}catch{return Response.json({error:'Invalid vote'},{status:400})}if(!candidates(grid,body.depth).some(c=>c.id===body.candidateId))return Response.json({error:'Candidate is not eligible in this session'},{status:400});try{await env.DB.prepare('INSERT INTO votes(session,voter,candidate,minutes,updated_at) VALUES(?,?,?,60,?) ON CONFLICT(session,voter) DO UPDATE SET candidate=excluded.candidate,updated_at=excluded.updated_at').bind(session(body.depth),body.voter,body.candidateId,Date.now()).run();return Response.json({accepted:true,minutes:60})}catch{return Response.json({error:'Vote was not saved. Please try again.'},{status:503})}}
