'use client';
import { useState } from 'react';
import Ocean from '@/components/ocean';
import { Waves, Layers, Compass, ArrowUpRight, Sparkles } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
export default function Explorer() {
 const [truth,setTruth]=useState(100);
 return <main className="abyss-app"><header className="topbar"><div className="brand"><Waves/><strong>ABYSS COMMONS</strong><span>MAP THE UNKNOWN</span></div><div className="snapshot-badge"><i/> AMERICAN SAMOA · SNAPSHOT 08 SEP 2026</div></header><div className="workspace"><aside className="layers-panel"><div className="eyebrow"><Layers size={15}/> EVIDENCE LAYERS</div><h2>How we know.</h2>{['Seafloor terrain','Source provenance','ROV activity','Biological records'].map((label,i)=><div className="layer" key={label}><span>{label}</span><Switch defaultChecked={i<2} aria-label={label}/></div>)}<div className="source-summary"><span className="eyebrow">THE LOCAL SNAPSHOT</span><p>480 × 240 terrain cells</p><p>4 recorded ROV tracks</p><p>323,640 public records</p></div></aside><section className="ocean-panel"><div className="map-heading"><span className="eyebrow">SOUTH PACIFIC / 01</span><h1>American Samoa</h1><p>14°–15° S · 169°–171° W</p></div><Ocean truth={truth} layers={{terrain:true,provenance:true,rov:false,obis:false,grid:false}} candidates={[]} selected={null} focusKey={0} onSelect={()=>{}} onTrack={()=>{}} onStatus={()=>{}}/><div className="truth-panel"><div className="eyebrow">WHAT DO WE ACTUALLY KNOW?</div><div className="truth-labels"><b>REALITY</b><span>INFERENCE</span></div><Slider value={[truth]} onValueChange={v=>setTruth(Array.isArray(v)?v[0]:v)} aria-label="Data provenance"/><p>This control filters data provenance, not statistical confidence.</p></div></section><aside className="astra-panel"><div className="panel-heading"><Sparkles size={18}/><h2>Astra</h2><span className="mode-chip">SNAPSHOT TOOLS</span></div><h3>Let evidence lead<br/>the next dive.</h3><p>Compare mapped terrain with recorded ROV activity and public biological observations.</p><button className="quick-prompt">Find an exploration candidate <ArrowUpRight size={17}/></button><div className="integrity-note">Astra is not connected yet. The scientific explorer will work independently.</div></aside></div><footer className="bottom-bar">GEBCO 2026 · NOAA Ocean Exploration · OBIS <span>Real data. Explicit uncertainty.</span></footer></main>;
}
