/* Browser-only QR URL and local ballot are synchronized after hydration. */
/* oxlint-disable react/react-compiler */
/* QR is a generated data URI, not a remote image requiring optimization. */
/* oxlint-disable next/no-img-element */
'use client';
import {useState,useEffect,useCallback} from 'react';
import QRCode from 'qrcode';
import type {Candidate} from '@/lib/abyss/types';
export default function Voting({minDepth=2000}:{minDepth?:number}){const [data,setData]=useState<{candidates:Candidate[];totals:Record<string,number>;winners:string[]}|null>(null),[error,setError]=useState(''),[picked,setPicked]=useState(''),[busy,setBusy]=useState(false),[qr,setQr]=useState(''),[url,setUrl]=useState('');
 const refresh=useCallback(async()=>{try{const r=await fetch(`/api/votes?depth=${Math.round(minDepth)}`);if(!r.ok)throw Error('Community voting is temporarily unavailable.');setData(await r.json());setError('')}catch(e){setError((e as Error).message)}},[minDepth]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),5000);const link=`${location.origin}/vote?depth=${Math.round(minDepth)}`;setUrl(link);void QRCode.toDataURL(link,{width:180,margin:1,color:{dark:'#08162a',light:'#eaf2f8'}}).then(setQr);try{setPicked(localStorage.getItem(`abyss-vote-${minDepth}`)??'')}catch{}return()=>clearInterval(timer)},[refresh,minDepth]);
 async function vote(id:string){setBusy(true);try{let voter=localStorage.getItem('abyss-voter');if(!voter){voter=crypto.randomUUID();localStorage.setItem('abyss-voter',voter)}const r=await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({depth:Math.round(minDepth),voter,candidateId:id})});if(!r.ok)throw Error('Vote was not saved. Try again.');setPicked(id);localStorage.setItem(`abyss-vote-${minDepth}`,id);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="voting"><p>Give all 60 virtual minutes to one candidate. You can change your choice. One ballot per browser, with community totals refreshed every 5 seconds.</p>{error&&<p className="vote-error" role="alert">{error}</p>}{data?.candidates.map(c=><button key={c.id} disabled={busy} className={'ballot '+(data.winners.includes(c.id)?'winning ':'')+(picked===c.id?'picked':'')} onClick={()=>void vote(c.id)}><span className="candidate-letter">{c.archetype}</span><span><strong>{c.title}</strong><small>{Math.round(c.meanDepth).toLocaleString()} m · {data.totals[c.id]} virtual minutes</small></span><b>{picked===c.id?'✓':'＋60'}</b></button>)}{data&&!data.candidates.length&&<p>No eligible candidates at this depth.</p>}{data&&data.winners.length===0&&<p>No votes yet. Choose the first destination.</p>}{picked&&<p className="vote-confirm">Your 60 virtual minutes are saved.</p>}<div className="vote-share">{qr&&<img src={qr} alt="QR code to open this voting session" width={120} height={120}/>}<div><strong>Bring the community in.</strong><p>Scan to vote on your phone.</p><a href={url} target="_blank" rel="noreferrer">Open voting page ↗</a><small>Minimum mean depth: {Math.round(minDepth).toLocaleString()} m</small></div></div></div>;
}
