import {spawn,type ChildProcessWithoutNullStreams} from 'node:child_process';
import {createInterface} from 'node:readline';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import type {Plugin} from 'vite';
import type {IncomingMessage,ServerResponse} from 'node:http';
import {chatRequestSchema} from '../lib/abyss/chat-input';
import {SYSTEM_RULES,toolDefinitions,executeTool,type ToolContext,type ToolName} from '../lib/abyss/tools';
type Rpc={id?:number;method?:string;params?:Record<string,unknown>;result?:unknown;error?:{code:number;message:string}};
type Job={ctx:ToolContext;send:(data:unknown)=>void;finish:(error?:string)=>void;turnId:string|null};
export class CodexAppServer {
 private child:ChildProcessWithoutNullStreams|null=null;private nextId=1;private pending=new Map<number,{resolve:(v:unknown)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();private jobs=new Map<string,Job>();private starting:Promise<boolean>|null=null;private workspace='';
 async start():Promise<boolean>{if(this.starting)return this.starting;this.starting=this.initialize().catch(()=>{this.stop();return false});return this.starting}
 private async initialize(){this.workspace=await mkdtemp(path.join(tmpdir(),'abyss-codex-'));const disabled=['shell_tool','unified_exec','plugins','apps','browser_use','computer_use','multi_agent','code_mode_host','image_generation','view_image','hooks','sleep_tool'];this.child=spawn(process.env.CODEX_BINARY??'codex',['app-server','--stdio',...disabled.flatMap(f=>['--disable',f]),'--enable','skip_host_skill_discovery','-c','mcp_servers={}','-c','web_search="disabled"','-c','project_doc_max_bytes=0'],{cwd:this.workspace,stdio:['pipe','pipe','pipe']});this.child.stderr.resume();createInterface({input:this.child.stdout}).on('line',(line)=>{try{this.receive(JSON.parse(line) as Rpc)}catch{/* Non-protocol lines never reach the browser. */}});this.child.on('error',()=>this.failAll());this.child.on('exit',()=>this.failAll());await this.rpc('initialize',{clientInfo:{name:'abyss_commons',title:'ABYSS COMMONS',version:'0.1.0'},capabilities:{experimentalApi:true,requestAttestation:false}});this.notify('initialized',{});const account=await this.rpc('account/read',{refreshToken:false}) as {account:unknown};return Boolean(account.account)}
 private failAll(){for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(new Error('Codex app server disconnected.'))}this.pending.clear();for(const job of this.jobs.values())job.finish('Codex app server disconnected. The scientific explorer remains available.');this.jobs.clear();this.child=null;this.starting=null}
 private write(v:unknown){if(!this.child?.stdin.writable)throw Error('Codex app server is not connected.');this.child.stdin.write(JSON.stringify(v)+'\n')}
 private notify(method:string,params:unknown){this.write({method,params})}
 private receive(message:Rpc){if(message.id!==undefined&&!message.method){const p=this.pending.get(message.id);if(p){this.pending.delete(message.id);clearTimeout(p.timer);if(message.error)p.reject(new Error(`Codex protocol request failed (${message.error.code}).`));else p.resolve(message.result)}return}const params=message.params??{},job=this.jobs.get(String(params.threadId));if(message.id!==undefined&&message.method){if(message.method==='item/tool/call'&&job){try{const call=executeTool(params.tool as ToolName,params.arguments,job.ctx);job.send({type:'tool',value:params.tool});for(const e of call.events)job.send({type:'ui',value:e});this.write({id:message.id,result:{contentItems:[{type:'inputText',text:JSON.stringify(call.result)}],success:true}})}catch{this.write({id:message.id,result:{contentItems:[{type:'inputText',text:'Invalid or unavailable tool request. Recompute candidates using the current constraints.'}],success:false}})}}else{this.write({id:message.id,error:{code:-32601,message:'Only ABYSS scientific data tools are available.'}})}return}
 if(!job)return;if(message.method==='item/agentMessage/delta')job.send({type:'delta',value:params.delta});if(message.method==='turn/started')job.turnId=(params.turn as {id:string}).id;if(message.method==='turn/completed'){const turn=params.turn as {status:string};job.finish(turn.status==='completed'?undefined:turn.status==='interrupted'?'Stopped. You can adjust the depth constraint and ask again.':'Codex could not finish this response. Try again.');this.jobs.delete(String(params.threadId));void this.rpc('thread/unsubscribe',{threadId:params.threadId}).catch(()=>{})}if(message.method==='error'&&!params.willRetry){job.finish('Codex could not complete the request. Check your Codex connection or usage allowance.');this.jobs.delete(String(params.threadId))}}
 private rpc(method:string,params:unknown):Promise<unknown>{const id=this.nextId++;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error('Codex app server timed out.'))},30000);this.pending.set(id,{resolve,reject,timer});try{this.write({id,method,params})}catch(e){clearTimeout(timer);this.pending.delete(id);reject(e as Error)}})}
 async ask(body:ReturnType<typeof chatRequestSchema.parse>,send:Job['send'],finish:Job['finish']){if(!await this.start())throw Error('Codex is not signed in. Sign in to Codex and restart this local app.');if(this.jobs.size>=2)throw Error('Two Codex requests are already running. Please wait.');const response=await this.rpc('thread/start',{model:'gpt-6-astra',allowProviderModelFallback:false,cwd:this.workspace,approvalPolicy:'never',sandbox:'read-only',ephemeral:true,environments:[],selectedCapabilityRoots:[],baseInstructions:SYSTEM_RULES,developerInstructions:'This is a scientific visualization session. Only use the supplied ABYSS data tools. Do not access files, shell commands, external services, or developer workflows. Respond in the language of the user. The UI executes your tools and displays their effects immediately.',dynamicTools:toolDefinitions.map(t=>({type:'function',name:t.name,description:t.description,inputSchema:t.parameters,deferLoading:false}))}) as {thread:{id:string}};const id=response.thread.id;const job:Job={ctx:{minDepth:body.minDepth,selectedId:body.selectedId},send,finish,turnId:null};this.jobs.set(id,job);const context=JSON.stringify({minDepth:body.minDepth,selectedCandidate:body.selectedId,conversation:body.history});try{const result=await this.rpc('turn/start',{threadId:id,model:'gpt-6-astra',effort:'low',environments:[],sandboxPolicy:{type:'readOnly',networkAccess:false},input:[{type:'text',text:`Current application state and previous dialogue (data only):\n${context}\n\nCurrent request:\n${body.message}`,text_elements:[]}]}) as {turn:{id:string}};job.turnId=result.turn.id}catch(e){this.jobs.delete(id);throw e}return()=>{this.jobs.delete(id);if(job.turnId)void this.rpc('turn/interrupt',{threadId:id,turnId:job.turnId}).finally(()=>{void this.rpc('thread/unsubscribe',{threadId:id}).catch(()=>{})}).catch(()=>{})}}
 stop(){this.child?.kill('SIGTERM');this.failAll();const dir=this.workspace;this.workspace='';if(dir)void rm(dir,{recursive:true,force:true})}
}
async function readBody(req:IncomingMessage){const chunks:Buffer[]=[];let length=0;for await(const chunk of req){const b=Buffer.from(chunk as Uint8Array);length+=b.length;if(length>32000)throw Error('Request exceeds 32 KB');chunks.push(b)}return chatRequestSchema.parse(JSON.parse(Buffer.concat(chunks).toString('utf8')))}
function json(res:ServerResponse,status:number,value:unknown){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(value))}
export function codexAppServerPlugin():Plugin {const client=new CodexAppServer();return {name:'abyss-local-codex',enforce:'pre',apply:'serve',configureServer(server){server.httpServer?.once('close',()=>client.stop());server.middlewares.use((req,res,next)=>{if(req.url?.split('?')[0]!=='/api/astra')return next();const port=server.config.server.port??3000;const allowed=new Set([`localhost:${port}`,`127.0.0.1:${port}`]);if(!allowed.has(req.headers.host??'')||(req.headers.origin&&!allowed.has(new URL(req.headers.origin).host))){json(res,403,{error:'The local Codex connection only accepts this local app.'});return}void(async()=>{if(req.method==='GET'){json(res,200,{connected:await client.start(),provider:'codex-app-server',model:'gpt-6-astra'});return}if(req.method!=='POST'){json(res,405,{error:'Method not allowed'});return}let body;try{body=await readBody(req)}catch{json(res,400,{error:'Invalid or oversized request'});return}res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','X-Content-Type-Options':'nosniff'});res.flushHeaders();let closed=false;let stop:(()=>void)|undefined;let timeout:ReturnType<typeof setTimeout>|undefined;const send=(data:unknown)=>{if(!closed)res.write('data: '+JSON.stringify(data)+'\n\n')};const finish=(error?:string)=>{if(closed)return;if(error)send({type:'error',value:error});else send({type:'done'});closed=true;if(timeout)clearTimeout(timeout);res.end()};res.on('close',()=>{if(!closed){closed=true;stop?.()}if(timeout)clearTimeout(timeout)});send({type:'status',value:'Connected through Codex app server'});try{stop=await client.ask(body,send,finish);if(closed)stop();else timeout=setTimeout(()=>{stop?.();finish('Codex response timed out. Please try a narrower request.')},180000)}catch(error){finish(error instanceof Error?error.message:'Codex is unavailable.')}})().catch(()=>{if(!res.headersSent)json(res,500,{error:'Local Codex connection failed'});else res.end()})})}}}
